# Generated by Django 5.2 on 2025-04-18 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Receptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_circuito", models.CharField(max_length=50)),
                ("num_receptor", models.CharField(max_length=50)),
                ("iav", models.FloatField(blank=True, null=True)),
                ("ith", models.FloatField(blank=True, null=True)),
                ("relacao", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "estacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receptores",
                        to="cdv_api.estacao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transmissor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_circuito", models.CharField(max_length=50)),
                ("num_transmissor", models.CharField(max_length=50)),
                ("vout", models.FloatField(blank=True, null=True)),
                ("pout", models.FloatField(blank=True, null=True)),
                ("tap", models.CharField(blank=True, max_length=20)),
                ("tipo_transmissor", models.CharField(blank=True, max_length=50)),
                (
                    "estacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transmissores",
                        to="cdv_api.estacao",
                    ),
                ),
            ],
        ),
    ]
