# Generated by Django 5.2 on 2025-04-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cdv_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receptor",
            old_name="num_receptor",
            new_name="num_circuito_rx",
        ),
    ]
