# Generated by Django 5.2 on 2025-04-18 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cdv_api", "0002_rename_num_receptor_receptor_num_circuito_rx"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receptor",
            old_name="num_circuito_rx",
            new_name="num_receptor",
        ),
    ]
