# Generated by Django 5.2 on 2025-04-29 05:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cdv_api", "0003_rename_num_circuito_rx_receptor_num_receptor"),
    ]

    operations = [
        migrations.AddField(
            model_name="receptor",
            name="data_manutencao",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="transmissor",
            name="data_manutencao",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
