# Generated by Django 5.2.3 on 2025-07-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdv_api', '0004_receptor_data_manutencao_transmissor_data_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptor',
            name='tipo_manutencao',
            field=models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('checklist', 'Checklist')], default='preventiva', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transmissor',
            name='tipo_manutencao',
            field=models.CharField(choices=[('preventiva', 'Preventiva'), ('corretiva', 'Corretiva'), ('checklist', 'Checklist')], default='preventiva', max_length=20),
            preserve_default=False,
        ),
    ]
