# Generated by Django 5.2.6 on 2025-10-13 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdv_api', '0005_receptor_tipo_manutencao_transmissor_tipo_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptor',
            name='data_coleta',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 10, 13, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receptor',
            name='hora_coleta',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora da coleta'),
        ),
        migrations.AddField(
            model_name='receptor',
            name='horario_coleta',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transmissor',
            name='data_coleta',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2025, 10, 13, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transmissor',
            name='hora_coleta',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora da coleta'),
        ),
    ]
