# Generated by Django 5.2.6 on 2025-10-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdv_api', '0006_receptor_data_coleta_receptor_hora_coleta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptor',
            name='data_coleta',
        ),
        migrations.RemoveField(
            model_name='receptor',
            name='hora_coleta',
        ),
        migrations.RemoveField(
            model_name='transmissor',
            name='data_coleta',
        ),
        migrations.RemoveField(
            model_name='transmissor',
            name='hora_coleta',
        ),
        migrations.AddField(
            model_name='transmissor',
            name='horario_coleta',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
