# Generated by Django 5.2.6 on 2025-10-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdv_api', '0007_remove_receptor_data_coleta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptor',
            name='temp_celsius',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transmissor',
            name='temp_celsius',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
