# Generated by Django 5.2.7 on 2026-03-23 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdv_api', '0008_receptor_temp_celsius_transmissor_temp_celsius'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineCDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_circuito', models.CharField(max_length=50)),
                ('vout_ref', models.FloatField(blank=True, null=True, verbose_name='VOUT de referência')),
                ('pout_ref', models.FloatField(blank=True, null=True, verbose_name='POUT de referência')),
                ('tap_ref', models.IntegerField(blank=True, null=True, verbose_name='TAP de referência')),
                ('tipo_tx_ref', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo TX de referência')),
                ('iav_ref', models.FloatField(blank=True, null=True, verbose_name='IAV de referência')),
                ('ith_ref', models.FloatField(blank=True, null=True, verbose_name='ITH de referência')),
                ('relacao_ref', models.FloatField(blank=True, null=True, verbose_name='Relação de referência')),
                ('data_comissionamento', models.DateField(verbose_name='Data do comissionamento')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('estacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='cdv_api.estacao')),
            ],
            options={
                'verbose_name': 'Baseline CDV',
                'verbose_name_plural': 'Baselines CDV',
                'ordering': ['estacao__nome', 'num_circuito'],
                'unique_together': {('estacao', 'num_circuito')},
            },
        ),
    ]
