# Generated by Django 5.2.7 on 2026-03-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdv_api', '0009_baselinecdv'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='baselinecdv',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='baselinecdv',
            constraint=models.UniqueConstraint(fields=('estacao', 'num_circuito'), name='unique_baseline_por_estacao_circuito'),
        ),
    ]
